/**
 * Deck-session activation guard shared by every Deck Pi extension.
 *
 * Deck extensions are materialized globally and therefore load in EVERY Pi session, including plain `pi`.
 * They must stay inert unless the session was launched by Deck (`DECK_PI_SESSION=1`). Children spawned by the
 * Deck subagent tool inherit the environment and set `DECK_PI_CHILD=1` plus their `DECK_PI_ROLE`.
 */
export const DECK_PI_SESSION_ENV = "DECK_PI_SESSION";
export const DECK_PI_ROLE_ENV = "DECK_PI_ROLE";
export const DECK_PI_CHILD_ENV = "DECK_PI_CHILD";

export type DeckPiEnv = Readonly<Record<string, string | undefined>>;

export type DeckPiActivation = Readonly<{
  active: boolean;
  child: boolean;
  lead: boolean;
  role: string | undefined;
}>;

export type DeckPiExtensionScope = "any" | "lead" | "child";

export function readDeckPiActivation(env: DeckPiEnv = process.env): DeckPiActivation {
  const active = env[DECK_PI_SESSION_ENV] === "1";
  if (!active) return { active: false, child: false, lead: false, role: undefined };
  const child = env[DECK_PI_CHILD_ENV] === "1";
  const role = env[DECK_PI_ROLE_ENV]?.trim() || "lead";
  return { active: true, child, lead: !child && role === "lead", role };
}

export function deckPiSessionEnv(role: string, options: { child?: boolean } = {}): Record<string, string> {
  return {
    [DECK_PI_SESSION_ENV]: "1",
    [DECK_PI_ROLE_ENV]: role,
    ...(options.child ? { [DECK_PI_CHILD_ENV]: "1" } : {}),
  };
}

function scopeMatches(activation: DeckPiActivation, scope: DeckPiExtensionScope): boolean {
  if (!activation.active) return false;
  if (scope === "lead") return activation.lead;
  if (scope === "child") return activation.child;
  return true;
}

/** Wraps an extension factory so it registers nothing outside an eligible Deck session. */
export function guardDeckExtension<Pi>(
  factory: (pi: Pi) => void | Promise<void>,
  options: { env?: DeckPiEnv; scope?: DeckPiExtensionScope } = {},
): (pi: Pi) => Promise<void> {
  const scope = options.scope ?? "any";
  return async (pi: Pi): Promise<void> => {
    const activation = readDeckPiActivation(options.env ?? process.env);
    if (!scopeMatches(activation, scope)) return;
    await factory(pi);
  };
}

/**
 * Plain-JavaScript `index.js` that Pi discovers as `extensions/<name>/index.js`. It checks the guard BEFORE
 * importing the implementation bundle, so a non-Deck session never even evaluates Deck extension code.
 */
export function renderGuardedExtensionEntry(options: { implFile: string; scope?: DeckPiExtensionScope; nativeShell?: boolean }): string {
  const scope = options.scope ?? "any";
  return [
    "// Generated by Deck. Inert unless the Pi session was launched by Deck (DECK_PI_SESSION=1).",
    ...(options.nativeShell ? ['import * as nativeShell from "@earendil-works/pi-coding-agent";'] : []),
    `const scope = ${JSON.stringify(scope)};`,
    "export default async function deckGuardedExtension(pi) {",
    "  const env = process.env;",
    '  if (env.DECK_PI_SESSION !== "1") return;',
    '  const child = env.DECK_PI_CHILD === "1";',
    '  const role = (env.DECK_PI_ROLE || "").trim() || "lead";',
    '  if (scope === "lead" && (child || role !== "lead")) return;',
    '  if (scope === "child" && !child) return;',
    `  const implementation = await import(${JSON.stringify(options.implFile)});`,
    '  const factory = implementation.default;',
    options.nativeShell ? '  if (typeof factory === "function") await factory(pi, nativeShell);' : '  if (typeof factory === "function") await factory(pi);',
    "}",
    "",
  ].join("\n");
}
