import { readFileSync } from "node:fs";

import subagentsAsset from "../assets/pi/extensions/deck-subagents.generated.js" with { type: "file" };

/** Names of the Deck-owned Pi extension bundles generated by `scripts/generate-pi-extension-assets.ts`. */
export type DeckPiExtensionBundleName = "deck-memory" | "deck-subagents" | "deck-tool-policy";

const ASSETS: Partial<Record<DeckPiExtensionBundleName, unknown>> = {
  "deck-subagents": subagentsAsset,
};

/** Node-loadable ESM source of a packaged Deck extension (embedded in the compiled CLI via `with { type: "file" }`). */
export function readDeckPiExtensionBundle(name: DeckPiExtensionBundleName): string {
  const asset = ASSETS[name];
  if (asset === undefined) throw new Error(`Deck Pi extension bundle "${name}" is not packaged.`);
  return readFileSync(typeof asset === "string" ? asset : new URL(`../assets/pi/extensions/${name}.generated.js`, import.meta.url), "utf-8");
}
