import { assertDigest, assertExactKeys, assertId, assertPlainRecord, cloneCanonical, codeValue, deepFreeze, denseArray, enumValue, repositoryPath, sha256Digest, stringArray, stringValue, timestampValue, type RepositoryPathContextV1, type Sha256Digest } from "./canonical";
export type BatchId = `batch:v1:${string}`; export type VerificationStage = "targeted"|"affected_area"|"broad";
export interface VerificationStagePlanV1 { stage: VerificationStage; checkIds: readonly string[] }
export interface ProvenanceRefV1 { actor:string; artifact?:string; eventId?:string; issuedAt:string }
export interface ApplyBatchContractV1 { schema:"apply-batch-v1"; batchId:BatchId; digest:Sha256Digest; changeId:string; taskIds:readonly string[]; dependencies:readonly {before:string;after:string}[]; ownerRole:"apply-general"|"apply-backend"|"apply-frontend"; allowedTargets:readonly string[]; blockedTargets:readonly string[]; acceptanceObligations:readonly string[]; verificationPlan:readonly VerificationStagePlanV1[]; artifactDigests:Readonly<Record<string,Sha256Digest>>; authorizationGrantRef:Sha256Digest; provenance:ProvenanceRefV1 }
export type ApplyBatchInputV1=Omit<ApplyBatchContractV1,"batchId"|"digest">&{repositoryRoot?:string;batchId?:never;digest?:never};
const keys=["schema","changeId","taskIds","dependencies","ownerRole","allowedTargets","blockedTargets","acceptanceObligations","verificationPlan","artifactDigests","authorizationGrantRef","provenance","repositoryRoot"];
function payload(input:unknown, parsing=false): Omit<ApplyBatchContractV1,"batchId"|"digest"> {
  assertExactKeys(input,keys,"apply batch"); if(input.schema!=="apply-batch-v1") throw new Error("unsupported-contract-version");
  const context:RepositoryPathContextV1={repositoryRoot: typeof input.repositoryRoot==="string"?input.repositoryRoot:"."};
  const allowed=denseArray(input.allowedTargets,"allowedTargets").map((v,i)=>repositoryPath(stringValue(v,`allowedTargets[${i}]`),context,`allowedTargets[${i}]`)).sort();
  const blocked=denseArray(input.blockedTargets,"blockedTargets").map((v,i)=>repositoryPath(stringValue(v,`blockedTargets[${i}]`),context,`blockedTargets[${i}]`)).sort();
  if(new Set(allowed).size!==allowed.length||new Set(blocked).size!==blocked.length||allowed.some(v=>blocked.includes(v))) throw new Error("invalid-evidence: target-collision");
  const dependencies=denseArray(input.dependencies,"dependencies").map((v,i)=>{assertExactKeys(v,["before","after"],`dependencies[${i}]`);const before=codeValue(v.before,`dependencies[${i}].before`),after=codeValue(v.after,`dependencies[${i}].after`);if(before===after) throw new Error("invalid-evidence: dependencies");return{before,after};}).sort((a,b)=>`${a.before}\0${a.after}`.localeCompare(`${b.before}\0${b.after}`));
  const verificationPlan=denseArray(input.verificationPlan,"verificationPlan",3).map((v,i)=>{assertExactKeys(v,["stage","checkIds"],`verificationPlan[${i}]`);return{stage:enumValue(v.stage,["targeted","affected_area","broad"],`verificationPlan[${i}].stage`),checkIds:stringArray(v.checkIds,`verificationPlan[${i}].checkIds`,true)}});
  assertPlainRecord(input.artifactDigests,"artifactDigests"); const artifactDigests:Record<string,Sha256Digest>={}; for(const [p,d] of Object.entries(input.artifactDigests)){assertDigest(d,`artifactDigests.${p}`);const n=repositoryPath(p,context,`artifactDigests.${p}`);if(n in artifactDigests)throw new Error("invalid-evidence: normalized-key-collision");artifactDigests[n]=d;}
  assertDigest(input.authorizationGrantRef,"authorizationGrantRef"); assertExactKeys(input.provenance,["actor","artifact","eventId","issuedAt"],"provenance");
  const provenance={actor:codeValue(input.provenance.actor,"provenance.actor"),...(input.provenance.artifact===undefined?{}:{artifact:repositoryPath(input.provenance.artifact,context,"provenance.artifact")}),...(input.provenance.eventId===undefined?{}:{eventId:codeValue(input.provenance.eventId,"provenance.eventId")}),issuedAt:timestampValue(input.provenance.issuedAt,"provenance.issuedAt")};
  return cloneCanonical({schema:"apply-batch-v1",changeId:codeValue(input.changeId,"changeId"),taskIds:stringArray(input.taskIds,"taskIds",true),dependencies,ownerRole:enumValue(input.ownerRole,["apply-general","apply-backend","apply-frontend"],"ownerRole"),allowedTargets:allowed,blockedTargets:blocked,acceptanceObligations:stringArray(input.acceptanceObligations,"acceptanceObligations",true),verificationPlan,artifactDigests,authorizationGrantRef:input.authorizationGrantRef,provenance});
}
export function buildApplyBatchContractV1(input:ApplyBatchInputV1):ApplyBatchContractV1{const p=payload(input);const digest=sha256Digest(p);return deepFreeze({...p,batchId:`batch:v1:${digest.slice(7,39)}`,digest}) as ApplyBatchContractV1;}
export function parseApplyBatchContractV1(value:unknown):ApplyBatchContractV1{assertExactKeys(value,[...keys.filter(k=>k!=="repositoryRoot"),"batchId","digest"],"apply batch");assertId(value.batchId,"batch:v1:","batchId");assertDigest(value.digest,"digest");const{batchId,digest,...rest}=value;const p=payload(rest,true);const expected=sha256Digest(p);if(digest!==expected||batchId!==`batch:v1:${expected.slice(7,39)}`)throw new Error("invalid-evidence: apply batch digest");return deepFreeze({...p,batchId,digest}) as ApplyBatchContractV1;}
export function assertBatchReferenceV1(reference:{batchId:string;batchDigest:string},batch:ApplyBatchContractV1):void{if(reference.batchId!==batch.batchId||reference.batchDigest!==batch.digest)throw new Error("batch-reference-mismatch");}
