import { describe, expect, test } from "bun:test";
import { classifyInvalidExecutionInputV1, planExecutionDecisionV1, replayExecutionDecisionV1 } from "./execution-control-plane";

describe("C-R4 exact safe invalid-input identity", () => {
  test("cyclic dossier is frozen invalid-evidence", () => { const value: any = {}; value.self = value; const plan = planExecutionDecisionV1("active", value, { state: "missing", rationaleCode: "AUTHZ_MISSING" }, { state: "not-required", policyDigest: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }, { kind: "none" }, { kind: "none" }); expect([plan.reasonCode, Object.isFrozen(plan.replayRecord)]).toEqual(["invalid-evidence", true]); });
  test("prototype dossier has fixed identity", () => { expect(classifyInvalidExecutionInputV1(Object.create({ x: 1 }), "prototype").failure).toBe("prototype"); });
  test("throwing getter is non-throwing", () => { const value = Object.create(null, { x: { get() { throw new Error("secret"); } } }); expect(classifyInvalidExecutionInputV1(value, "malformed").failure).toBe("malformed"); });
  test("revoked proxy has unclassifiable fallback", () => { const target = Proxy.revocable({}, {}); target.revoke(); expect(classifyInvalidExecutionInputV1(target.proxy, "unknown").valueClass).toBe("unclassifiable"); });
  test("secret-bearing input is not serialized", () => { const identity = classifyInvalidExecutionInputV1({ secret: "do-not-persist" }, "unsafe"); expect(JSON.stringify(identity)).not.toContain("do-not-persist"); });
  test("unsupported contract version has fixed identity", () => { expect(classifyInvalidExecutionInputV1({ schema: "v99" }, "unsupported contract version").failure).toBe("unsupported-version"); });
  test("invalid record replay is deterministic", () => { const plan = planExecutionDecisionV1("shadow", { nope: 1 }, { state: "missing", rationaleCode: "AUTHZ_MISSING" }, { state: "not-required", policyDigest: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }, { kind: "none" }, { kind: "none" }); expect(replayExecutionDecisionV1(plan.replayRecord)).toBeUndefined(); });
  test("invalid class has canonical digest", () => { const a = planExecutionDecisionV1("active", { bad: 1 }, { state: "missing", rationaleCode: "AUTHZ_MISSING" }, { state: "not-required", policyDigest: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }, { kind: "none" }, { kind: "none" }); const b = planExecutionDecisionV1("active", { bad: 2 }, { state: "missing", rationaleCode: "AUTHZ_MISSING" }, { state: "not-required", policyDigest: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }, { kind: "none" }, { kind: "none" }); expect(a.inputDigest).toBe(b.inputDigest); });
  test("replay record is deeply frozen", () => { const plan = planExecutionDecisionV1("active", null, { state: "missing", rationaleCode: "AUTHZ_MISSING" }, { state: "not-required", policyDigest: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }, { kind: "none" }, { kind: "none" }); expect(Object.isFrozen(plan.replayRecord)).toBe(true); });
});
