/**
 * Bootstrap skill content for deck-onboard.
 * This skill onboard new developers to an existing Deck project.
 */

const deckOnboardSkillContentLines = [
  "---",
  'name: deck-onboard',
  'description: "Trigger: deck onboard, start sdd, learn sdd. Interactive SDD walkthrough using Deck\'s developer team."',
  "user-invocable: true",
  "disable-model-invocation: true",
  "license: MIT",
  "metadata:",
  '  author: deck',
  '  version: "1.0"',
  "---",
  "",
  "# deck-onboard Skill",
  "",
  "## PURPOSE",
  "",
  "You are responsible for ONBOARDING. Guide the user through a complete SDD cycle using their actual codebase and Deck's developer team agents. This is inline execution by the orchestrator - no sub-agent delegation needed.",
  "",
  "## HARD RULES",
  "",
  "1. **Check init first** - If openspec/config.yaml does not have initialized: true, return an error instructing the user to run deck-init first.",
  "2. **Inline execution** - You are NOT delegated; the orchestrator runs you directly. Do not attempt to delegate to yourself.",
  "3. **Use existing agents** - Delegate phases 2-9 to the EXISTING Deck developer team agents (deck-developer-explorer, deck-developer-proposal, etc.). Do NOT clone or reimplement their behavior.",
  "4. **User review gate** - Pause after Phase 3 (Proposal) and request user approval before proceeding to Phase 4 (Spec).",
  "5. **Narrate each phase** - Briefly explain what happens and why.",
  "",
  "## GUARD: INIT CHECK",
  "",
  "Before starting any work:",
  "",
  "1. Read openspec/config.yaml",
  "2. Verify initialized: true exists",
  "3. If missing or false, return:",
  "",
  "```ts",
  "interface OnboardError {",
  '  outcome: "init-required";',
  '  message: "Project not initialized. Run deck-init first to initialize SDD context.";',
  '  hint: "Invoke deck-init skill to scan the codebase, index with codebase-memory, and bootstrap openspec.";',
  "}",
  "```",
  "",
  "---",
  "",
  "## PHASE 1: Welcome + Choose Improvement",
  "",
  "**Narration**: Phase 1 welcomes the user to Deck's SDD flow and helps them identify a small, safe improvement opportunity in their codebase. Choosing something modest ensures a successful first cycle and builds confidence.",
  "",
  "### Steps",
  "",
  "1. Display welcome message:",
  "   - Introduce Deck's 10-phase SDD workflow",
  "   - Explain that this walkthrough teaches the full cycle hands-on",
  "   - Mention it uses their actual project files",
  "",
  "2. Scan for improvement opportunities:",
  "   - Look for small files (<200 lines) in src/ or lib/",
  "   - Identify files with obvious patterns: TODO comments, FIXME markers, unused exports, dead code",
  "   - Present 2-3 options to the user",
  "",
  "3. Let user choose the focus area",
  "",
  "### Output: Choice Confirmation",
  "",
  "```ts",
  "interface Phase1Result {",
  "  phase: 1;",
  "  chosen: string;",
  "  file_path: string;",
  '  improvement_type: "cleanup" | "refactor" | "feature" | "fix";',
  "}",
  "```",
  "",
  "---",
  "",
  "## PHASE 2: Explore",
  "",
  "**Narration**: Phase 2 delegates to deck-developer-explorer to investigate the chosen improvement. The explorer analyzes the codebase structure, identifies constraints, and surfaces risks before any implementation commitment.",
  "",
  "### Delegation",
  "",
  "Call: skill name: deck-developer-explorer with:",
  "- Target file or area from Phase 1",
  "- Context: what the user wants to accomplish",
  "",
  "### Expected Output",
  "",
  "```ts",
  "interface ExplorerResult {",
  "  phase: 2;",
  "  findings: {",
  "    structure?: string;",
  "    constraints?: string[];",
  "    risks?: string[];",
  "    approach?: string;",
  "  };",
  "}",
  "```",
  "",
  "### Narrative Summary",
  "",
  "Present explorer findings in 1-3 sentences:",
  "- What's in the codebase",
  "- Any constraints discovered",
  "- Recommended approach",
  "",
  "---",
  "",
  "## PHASE 3: Proposal",
  "",
  "**Narration**: Phase 3 delegates to deck-developer-proposal to formalize the improvement as a change proposal. A proposal captures intent, scope, risks, and rollback - creating a record before spec work begins.",
  "",
  "### Delegation",
  "",
  "Call: skill name: deck-developer-proposal with:",
  "- Explorer findings from Phase 2",
  "- User's chosen improvement",
  "",
  "### Expected Output",
  "",
  "```ts",
  "interface ProposalResult {",
  "  phase: 3;",
  "  proposal_id: string;",
  "  title: string;",
  "  intent: string;",
  "  scope: string;",
  "  risks: string[];",
  "  rollback: string;",
  "}",
  "```",
  "",
  "### Narrative Summary",
  "",
  "Summarize the proposal in 1-3 sentences:",
  "- What will change",
  "- Scope boundaries",
  "- Key risks identified",
  "",
  "---",
  "",
  "## USER REVIEW GATE",
  "",
  "**STOP HERE.** Present the proposal to the user for review.",
  "",
  "Request confirmation:",
  "",
  "```markdown",
  "## Proposal Review",
  "",
  "**Title**: PROPOSAL_TITLE",
  "**Intent**: PROPOSAL_INTENT",
  "**Scope**: PROPOSAL_SCOPE",
  "",
  "Potential risks:",
  "- RISK_1",
  "- RISK_2",
  "",
  "**Do you approve proceeding to specification?** (yes/no)",
  "",
  "If no: STOP. Return partial summary of completed phases (1-3).",
  "```",
  "",
  "If user responds 'no' or declines:",
  "- Return cancellation envelope",
  "- List completed phases",
  "- SuggestDeck commands for retry",
  "",
  "If user responds 'yes':",
  "- Proceed to Phase 4",
  "",
  "---",
  "",
  "## PHASE 4: Spec",
  "",
  "**Narration**: Phase 4 delegates to deck-developer-spec to define formal requirements and acceptance scenarios. The spec transforms the proposal into testable criteria - the contract that verify will check against.",
  "",
  "### Delegation",
  "",
  "Call: skill name: deck-developer-spec with:",
  "- Approved proposal from Phase 3",
  "",
  "### Expected Output",
  "",
  "```ts",
  "interface SpecResult {",
  "  phase: 4;",
  "  spec_id: string;",
  "  requirements: {",
  "    id: string;",
  "    description: string;",
  '    priority: "MUST" | "SHOULD" | "COULD";',
  "  }[];",
  "  scenarios: {",
  "    given: string;",
  "    when: string;",
  "    then: string;",
  "  }[];",
  "}",
  "```",
  "",
  "### Narrative Summary",
  "",
  "Explain in 1-3 sentences:",
  "- What the spec defines",
  "- Key requirements being captured",
  "- How acceptance will be measured",
  "",
  "---",
  "",
  "## PHASE 5: Design",
  "",
  "**Narration**: Phase 5 delegates to deck-developer-design to define the technical architecture and implementation approach. Design translates requirements into file impact and code strategy.",
  "",
  "### Delegation",
  "",
  "Call: skill name: deck-developer-design with:",
  "- Spec from Phase 4",
  "- Explorer findings from Phase 2",
  "",
  "### Expected Output",
  "",
  "```ts",
  "interface DesignResult {",
  "  phase: 5;",
  "  design_id: string;",
  "  architecture: string;",
  "  file_impacts: {",
  "    path: string;",
  '    action: "create" | "modify" | "delete";',
  "  }[];",
  "  approach: string;",
  "  tradeoffs: string[];",
  "}",
  "```",
  "",
  "### Narrative Summary",
  "",
  "Summarize in 1-3 sentences:",
  "- Key architectural decisions",
  "- Files that will change",
  "- Tradeoffs made",
  "",
  "---",
  "",
  "## PHASE 6: Tasks",
  "",
  "**Narration**: Phase 6 delegates to deck-developer-task to break the design into atomic, routable implementation tasks. Each task is a single logical change assigned to the appropriate apply agent.",
  "",
  "### Delegation",
  "",
  "Call: skill name: deck-developer-task with:",
  "- Design from Phase 5",
  "",
  "### Expected Output",
  "",
  "```ts",
  "interface TaskResult {",
  "  phase: 6;",
  "  tasks: {",
  "    id: string;",
  "    description: string;",
  '    agent: "backend" | "frontend" | "general";',
  "    dependencies?: string[];",
  "  }[];",
  "}",
  "```",
  "",
  "### Narrative Summary",
  "",
  "Briefly describe:",
  "- How many tasks created",
  "- Which agents will execute them",
  "- Execution order",
  "",
  "---",
  "",
  "## PHASE 7: Apply",
  "",
  "**Narration**: Phase 7 delegates to the appropriate Deck apply agents (deck-developer-apply-backend, deck-developer-apply-frontend, or deck-developer-apply-general) to implement each task. This is where changes actually happen to the codebase.",
  "",
  "### Delegation Pattern",
  "",
  "For each task in Phase 6:",
  "1. Determine agent type from task.agent field",
  "2. Call corresponding skill:",
  "   - skill name: deck-developer-apply-backend for backend tasks",
  "   - skill name: deck-developer-apply-frontend for frontend tasks",
  "   - skill name: deck-developer-apply-general for shared/general tasks",
  "",
  "### Expected Output",
  "",
  "```ts",
  "interface ApplyResult {",
  "  phase: 7;",
  "  task_id: string;",
  '  status: "completed" | "blocked" | "partial";',
  "  files_changed: string[];",
  "  notes?: string;",
  "}",
  "```",
  "",
  "### Narrative Summary",
  "",
  "After all tasks complete:",
  "- Summarize changes made",
  "- Note any blockers encountered",
  "- Confirm files modified",
  "",
  "---",
  "",
  "## PHASE 8: Verify",
  "",
  "**Narration**: Phase 8 delegates to deck-developer-verify to check compliance with specs, tasks, tests, and build/typecheck. Verify ensures the implementation actually meets the criteria defined in Phase 4.",
  "",
  "### Delegation",
  "",
  "Call: skill name: deck-developer-verify with:",
  "- Spec from Phase 4",
  "- Tasks from Phase 6",
  "- Apply results from Phase 7",
  "",
  "### Expected Output",
  "",
  "```ts",
  "interface VerifyResult {",
  "  phase: 8;",
  "  checks: {",
  "    spec_compliant: boolean;",
  "    tests_pass: boolean;",
  "    build_valid: boolean;",
  "    typecheck_valid: boolean;",
  "  };",
  "  issues?: string[];",
  "}",
  "```",
  "",
  "### Narrative Summary",
  "",
  "Report in 1-3 sentences:",
  "- Overall verification status",
  "- Any issues found",
  "- Resolution if applicable",
  "",
  "---",
  "",
  "## PHASE 9: Archive",
  "",
  "**Narration**: Phase 9 delegates to deck-developer-archive to close the change, preserve traceability, and update project records. Archive creates lasting artifacts - proposal, spec, and design documents are saved and linked.",
  "",
  "### Delegation",
  "",
  "Call: skill name: deck-developer-archive with:",
  "- Proposal from Phase 3",
  "- Spec from Phase 4",
  "- Design from Phase 5",
  "",
  "### Expected Output",
  "",
  "```ts",
  "interface ArchiveResult {",
  "  phase: 9;",
  "  artifacts: {",
  "    proposal_path: string;",
  "    spec_path: string;",
  "    design_path?: string;",
  "  };",
  '  status: "completed";',
  "}",
  "```",
  "",
  "### Narrative Summary",
  "",
  "Note in 1-2 sentences:",
  "- Artifacts preserved",
  "- Where they are stored",
  "",
  "---",
  "",
  "## PHASE 10: Summary",
  "",
  "**Narration**: Phase 10 presents the completion envelope and recommends next steps. The user has completed a full SDD cycle and understands Deck's workflow.",
  "",
  "### Completion Envelope",
  "",
  "```ts",
  "interface OnboardSummary {",
  '  outcome: "completed";',
  "  phases_completed: 10;",
  '  workflow: "SDD";',
  "  artifacts_created: {",
  "    proposal: string;",
  "    spec: string;",
  "    design: string;",
  "    tasks: number;",
  "    changes: string[];",
  "  };",
  "  next_recommended: {",
  "    command: string;",
  "    description: string;",
  "  }[];",
  "}",
  "```",
  "",
  "### Final Message",
  "",
  "```markdown",
  "## Walkthrough Complete",
  "",
  "Congratulations! You have completed a full SDD cycle with Deck.",
  "",
  "**Artifacts Created:**",
  "- Proposal: PATH",
  "- Spec: PATH",
  "- Design: PATH",
  "- Implementation: N file(s) changed",
  "",
  "**What Just Happened:**",
  "1. We explored your codebase and found a small improvement",
  "2. Formalized it as a proposal with risks and rollback",
  "3. Spec'd requirements and acceptance scenarios",
  "4. Designed the architecture and file impacts",
  "5. Broke work into tasks for apply agents",
  "6. Applied changes to your codebase",
  "7. Verified compliance with tests/build/typecheck",
  "8. Archived artifacts for traceability",
  "9. Now we summarize and recommend next steps",
  "",
  "**Next Steps:**",
  "Run another SDD cycle: deck-onboard",
  "Or ask Deck about any other skill: learn skills",
  "```",
  "",
  "---",
  "",
  "## ERROR CONTRACT",
  "",
  "| Condition | Error Code | Message |",
  "|---|---|---|",
  "| Not initialized | INIT_REQUIRED | Project not initialized. Run deck-init first. |",
  "| User declines at gate | DECLINED | Walkthrough stopped after Phase 3. Proposal saved. |",
  "| Agent delegation fails | DELEGATE_FAILED | Failed to delegate to AGENT. Try running that agent directly. |",
  "| Verify fails | VERIFY_FAILED | Implementation does not meet spec. Review issues and retry apply. |",
];

export const deckOnboardSkillContent = deckOnboardSkillContentLines.join("\n");