/**
 * Bootstrap skill content for deck-init.
 * This skill initializes a new Deck project from scratch.
 */

const deckInitSkillContentLines = [
  "---",
  'name: deck-init',
  'description: "Trigger: deck init, initialize deck, startsdd. Initialize SDD context, index codebase, bootstrap openspec."',
  "user-invocable: false",
  "disable-model-invocation: true",
  "license: MIT",
  "metadata:",
  '  author: deck',
  '  version: "1.0"',
  "  delegate_only: true",
  "---",
  "",
  "# deck-init Skill",
  "",
  "## ORCHESTRATOR GATE",
  "",
  "If you loaded this via skill() tool, you are the ORCHESTRATOR - STOP. Delegate to the dedicated deck-init sub-agent.",
  "",
  "## Activation Contract",
  "",
  "Run when orchestrator/user asks to initialize SDD. Do the work yourself, do not delegate.",
  "",
  "## Hard Rules",
  "",
  "1. **Never guess** - detect real stack from files.",
  "2. **If openspec/config.yaml has initialized: true** - return already-initialized envelope, skip heavy work.",
  "3. **Always create/merge openspec/config.yaml** with initialized: true.",
  "4. **Use OpenSpec only** - OpenSpec is the only persistence layer.",
  "",
  "## Decision Gates",
  "",
  "| Condition | Outcome |",
  "|---|---|",
  "| initialized: true exists in openspec/config.yaml | outcome: already-initialized |",
  "| Fresh init | run full detection + index |",
  "| index fails | outcome: failed with error |",
  "",
  "## Execution Steps",
  "",
  "### Step 1: Detect Project Root",
  "",
  "Walk upward from cwd:",
  "- **Monorepo markers** (strong): pnpm-workspace.yaml, nx.json, turbo.json, lerna.json",
  "- **Strong markers**: package.json, go.mod, pyproject.toml, Cargo.toml",
  "- **Weak markers**: .git",
  "",
  "Stop at first match. Error if no root found.",
  "",
  "### Step 2: Detect Technology Stack",
  "",
  "Scan root for manifests:",
  "- **Node/JS**: package.json, package-lock.json, yarn.lock, pnpm-lock.yaml",
  "- **Go**: go.mod",
  "- **Python**: pyproject.toml, requirements.txt, setup.py",
  "- **Rust**: Cargo.toml",
  "- **Other**: detect from file extensions and patterns",
  "",
  "Collect found technologies in tech[].",
  "",
  "### Step 3: Detect Testing Capabilities",
  "",
  "Look for:",
  "- **Runner**: jest.config.js, vitest.config.ts, pytest.ini, Cargo.toml test config, etc.",
  "- **Layers**: /** / *.test.* , /** / *.spec.* , tests/, __tests__/, e2e/, integration/",
  "- **Coverage**: coverage/, .nycrc, jest.config.js coverage section, codecov.yml",
  "- **Linter**: .eslintrc, .pylintrc, rust-toolchain.toml clippy, etc.",
  "- **Type checker**: tsconfig.json, mypy.ini, rust-toolchain.toml annotations",
  "- **Formatter**: .prettierrc, black.toml, rustfmt.toml",
  "",
  "### Step 4: Detect Monorepo Structure",
  "",
  "Check for monorepo config at root:",
  "- pnpm-workspace.yaml - monorepo: true",
  "- nx.json - monorepo: true",
  "- turbo.json - monorepo: true",
  "- lerna.json - monorepo: true",
  "",
  "Default: monorepo: false",
  "",
  "### Step 5: Index Codebase",
  "",
  "Call: codebase-memory_index_repository with repo_path, mode: full, persistence: true",
  "",
  "Handle failure - outcome: failed.",
  "",
  "### Step 6: Create/Merge OpenSpec Config",
  "",
  "Write/merge openspec/config.yaml:",
  "",
  "```yaml",
  "initialized: true",
  "last_index: TIMESTAMP",
  "index_mode: full",
  "context: |",
  "  Tech stack: TECH_LIST",
  "  Testing: TESTING_SUMMARY",
  "  Monorepo: YES_NO",
  "```",
  "",
  "Preserve existing keys (especially rules:).",
  "",
  "### Step 7: Build Skill Registry",
  "",
  "Scan standard skill locations (use glob/find patterns):",
  "- user-level skills in agent-specific config directories",
  "- project-level skills in .skills/ or runner-vendor skill dirs",
  "",
  "Write .atl/skill-registry.md if possible.",
  "",
  "### Step 8: Return InitEnvelope",
  "",
  "```ts",
  "interface TestingCapabilities {",
  "  runner?: string;",
  "  layers?: (unit | integration | e2e)[];",
  "  coverage?: string;",
  "  linter?: string;",
  "  typeChecker?: string;",
  "  formatter?: string;",
  "}",
  "",
  "interface DetectedStack {",
  "  tech: string[];",
  "  testing: TestingCapabilities;",
  "  monorepo: boolean;",
  "}",
  "",
  "type InitOutcome = success | already-initialized | failed;",
  "",
  "interface InitEnvelope {",
  "  outcome: InitOutcome;",
  "  config_path: string;",
  "  detected_stack: DetectedStack;",
  "  index_status: indexed | skipped | failed;",
  "  error?: string;",
  "}",
  "```",
  "",
  "Return populated InitEnvelope with the detected information.",
  "",
  "## Output Contract",
  "",
  "```ts",
  "type InitEnvelope = {",
  "  outcome: success | already-initialized | failed;",
  "  config_path: string;",
  "  detected_stack: {",
  "    tech: string[];",
  "    testing: TestingCapabilities;",
  "    monorepo: boolean;",
  "  };",
  "  index_status: indexed | skipped | failed;",
  "  error?: string;",
  "};",
  "```",
];

export const deckInitSkillContent = deckInitSkillContentLines.join("\n");