/**
 * Generated build info for production builds.
 *
 * Auto-generated by scripts/generate-build-info.ts.
 * Do not edit manually.
 */

import type { BuildInfo } from "./build-info.js";

export const BUILD_INFO: BuildInfo = {
  version: "0.1.5",
  commit: "5454628",
  date: "2026-06-10",
  target: "linux-x64",
  channel: "stable",
} as const;
