#!/usr/bin/env bun
/**
 * Generate skill content bundle.
 *
 * Recursively reads all files in each skill directory and generates
 * a TypeScript module with full skill bundles.
 *
 * Usage: bun scripts/generate-skill-bundle.ts
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { STANDALONE_SKILLS } from "../packages/core/src/skills/external/index";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const EXTERNAL_SKILLS_DIR = join(ROOT, "packages/core/src/skills/external");
const OUTPUT_FILE = join(EXTERNAL_SKILLS_DIR, "content.generated.ts");

// Skill IDs come from the canonical runtime registry to prevent generator drift.
const CANONICAL_SKILLS = STANDALONE_SKILLS.map((skill) => skill.skillId);

function escapeStringForTs(str: string): string {
  // Escape backticks, ${, and backslashes for template literal
  return str
    .replace(/\\/g, "\\\\")
    .replace(/\$/g, "\\$")
    .replace(/`/g, "\\`")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

/**
 * Check if a filename should be excluded (system artifacts).
 */
function shouldExclude(name: string): boolean {
  // Skip Windows NTFS metadata files
  if (name.endsWith(":Zone.Identifier")) return true;
  // Skip macOS resource forks
  if (name.startsWith("._")) return true;
  return false;
}

/**
 * Recursively walk a skill directory and collect all files.
 * Returns a map of relative path to content.
 */
function walkSkillDirectory(skillDir: string): Record<string, string> {
  const files: Record<string, string> = {};

  function walk(dir: string, relPath: string = "") {
    const entries = readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (shouldExclude(entry.name)) continue;

      const fullPath = join(dir, entry.name);
      const entryRelPath = relPath ? join(relPath, entry.name) : entry.name;

      if (entry.isDirectory()) {
        walk(fullPath, entryRelPath);
      } else if (entry.isFile()) {
        try {
          const content = readFileSync(fullPath, "utf-8");
          // Use POSIX forward-slash for cross-platform consistency
          const normalizedPath = entryRelPath.replace(/\\/g, "/");
          files[normalizedPath] = content;
        } catch (err) {
          // Fail loudly on unreadable files per REQ-ESCG-003
          throw new Error(
            `Unable to read file ${fullPath}: ${err instanceof Error ? err.message : String(err)}`
          );
        }
      }
    }
  }

  walk(skillDir);
  return files;
}

function generateBundle(): void {
  const bundles: Record<string, { SKILL: string; files: Record<string, string> }> = {};
  const errors: string[] = [];

  for (const skillId of CANONICAL_SKILLS) {
    const skillDir = join(EXTERNAL_SKILLS_DIR, skillId);

    if (!existsSync(skillDir)) {
      errors.push(`Skill ${skillId} directory not found at ${skillDir}`);
      continue;
    }

    // Walk directory for all files
    const dirFiles = walkSkillDirectory(skillDir);

    // Require SKILL.md
    if (!dirFiles["SKILL.md"]) {
      errors.push(`Skill ${skillId} is missing SKILL.md`);
      continue;
    }

    const skillContent = dirFiles["SKILL.md"];
    if (!skillContent) {
      errors.push(`Skill ${skillId} SKILL.md is empty`);
      continue;
    }

    // Separate SKILL.md body from other files
    const { "SKILL.md": _skillBody, ...otherFiles } = dirFiles;

    bundles[skillId] = {
      SKILL: skillContent,
      files: otherFiles,
    };
  }

  // Check all canonical skills processed
  for (const skillId of CANONICAL_SKILLS) {
    if (!bundles[skillId]) {
      errors.push(`Skill ${skillId} not bundled`);
    }
  }

  if (errors.length > 0) {
    console.error("Error generating skill bundle:");
    for (const err of errors) {
      console.error(`  - ${err}`);
    }
    process.exit(1);
  }

  // Generate TypeScript module with inline StandaloneSkillBundle type
  const bundleEntries = Object.entries(bundles).map(([skillId, bundle]) => {
    const filesObj = Object.entries(bundle.files)
      .map(([filePath, content]) => `    "${escapeStringForTs(filePath)}": \`${escapeStringForTs(content)}\``,)
      .join(",\n");

    return `  "${skillId}": {
    SKILL: \`${escapeStringForTs(bundle.SKILL)}\`,
    files: {
${filesObj}
    },
  }`;
  });

  const tsContent = `/**
 * Generated skill content bundle.
 *
 * AUTO-GENERATED FILE — DO NOT EDIT
 * Generated by: scripts/generate-skill-bundle.ts
 */

/**
 * Inline type matching StandaloneSkillBundle contract.
 */
type StandaloneSkillBundle = {
  SKILL: string;
  files: Record<string, string>;
};

// prettier-ignore
export const STANDALONE_SKILL_BUNDLES: Record<string, StandaloneSkillBundle> = {
${bundleEntries.join(",\n")}
};

// Alias for backward compatibility with consumers expecting SKILL_BUNDLES
// prettier-ignore
export const SKILL_BUNDLES = STANDALONE_SKILL_BUNDLES;
`;

  // Write output
  const outputDir = dirname(OUTPUT_FILE);
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  writeFileSync(OUTPUT_FILE, tsContent, "utf-8");

  console.log(`Generated skill bundle: ${OUTPUT_FILE}`);
  console.log(`  Skills bundled: ${Object.keys(bundles).join(", ")}`);
}

// Run if called directly
if (import.meta.main) {
  generateBundle();
}
