import { isAbsolute, resolve } from "node:path";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const root = resolve(import.meta.dir, "..");
const entries = [
  {
    input: "packages/adapter-opencode/assets/opencode/plugins/developer-team-execution.ts",
    output: "packages/adapter-opencode/assets/opencode/plugins/developer-team-execution.generated.js",
  },
  {
    input: "packages/adapter-pi/assets/pi/extensions/developer-team-execution.ts",
    output: "packages/adapter-pi/assets/pi/extensions/developer-team-execution.generated.js",
  },
  {
    input: "packages/adapter-codex/assets/codex/hooks/developer-team-execution.ts",
    output: "packages/adapter-codex/assets/codex/hooks/developer-team-execution.generated.js",
  },
] as const;

type SpawnSync = typeof Bun.spawnSync;

export type RunnerExecutionAssetResult = {
  input: string;
  output: string;
  sourceDigest: string;
  bunPath: string;
  bunVersion: string;
};

export function readCanonicalBunVersionFromReleaseWorkflow(projectRoot = root): string {
  const workflow = readFileSync(resolve(projectRoot, ".github/workflows/release.yml"), "utf-8");
  const versions = [...workflow.matchAll(/\bbun-version\s*:\s*["']?([^"'\s#]+)["']?/g)].map((match) => match[1]);
  const distinct = [...new Set(versions)];
  if (distinct.length !== 1 || !/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(distinct[0])) {
    throw new Error(
      `Unable to determine one canonical Bun version from .github/workflows/release.yml; found ${distinct.length === 0 ? "none" : distinct.join(", ")}.`,
    );
  }
  return distinct[0];
}

function decode(data: Uint8Array): string {
  return new TextDecoder().decode(data).trim();
}

function executingBunVersion(projectRoot: string, spawnSync: SpawnSync): string {
  const bunPath = process.execPath;
  if (!isAbsolute(bunPath)) throw new Error(`Unable to resolve the executing Bun binary path: ${bunPath}`);
  const version = spawnSync({ cmd: [bunPath, "--version"], cwd: projectRoot, stdout: "pipe", stderr: "pipe" });
  if (!version.success) throw new Error(`Unable to execute ${bunPath} --version: ${decode(version.stderr)}`);
  return decode(version.stdout).split(/\s+/)[0] ?? "";
}

export function assertCanonicalBunRuntime(
  projectRoot = root,
  spawnSync: SpawnSync = Bun.spawnSync,
): { bunPath: string; bunVersion: string } {
  const expected = readCanonicalBunVersionFromReleaseWorkflow(projectRoot);
  const bunPath = process.execPath;
  const actual = executingBunVersion(projectRoot, spawnSync);
  if (actual !== expected) {
    throw new Error(
      [
        `Tracked asset generation requires Bun ${expected} from .github/workflows/release.yml, but the executing Bun at ${bunPath} is ${actual || "unknown"}.`,
        "No outputs were written.",
        `Run this script with a verified isolated Bun ${expected} binary or in the release workflow pinned toolchain; do not regenerate these assets with a different global or PATH-selected Bun.`,
      ].join(" "),
    );
  }
  return { bunPath, bunVersion: actual };
}

export function generateRunnerExecutionAssets(options: { root?: string; spawnSync?: SpawnSync } = {}): RunnerExecutionAssetResult[] {
  const projectRoot = options.root ?? root;
  const spawnSync = options.spawnSync ?? Bun.spawnSync;
  const { bunPath, bunVersion } = assertCanonicalBunRuntime(projectRoot, spawnSync);
  const generated: RunnerExecutionAssetResult[] = [];
  for (const entry of entries.map((candidate) => ({
    input: resolve(projectRoot, candidate.input),
    output: resolve(projectRoot, candidate.output),
  }))) {
    const build = spawnSync({
      cmd: [bunPath, "build", entry.input, "--target=bun", "--format=esm", "--minify", `--outfile=${entry.output}`],
      cwd: projectRoot,
      stdout: "pipe",
      stderr: "pipe",
    });
    if (!build.success) {
      throw new Error(decode(build.stderr));
    }
    const sourceDigest = createHash("sha256").update(readFileSync(entry.input)).digest("hex");
    const bundle = readFileSync(entry.output, "utf-8");
    writeFileSync(entry.output, `// Generated by scripts/generate-runner-execution-assets.ts; do not edit.\n// source-sha256:${sourceDigest}\n${bundle}`, "utf-8");
    generated.push({ ...entry, sourceDigest, bunPath, bunVersion });
  }
  return generated;
}

if (import.meta.main) {
  try {
    generateRunnerExecutionAssets();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
