#!/usr/bin/env bun
/**
 * Generate skill content bundle.
 *
 * Reads all canonical external skill SKILL.md files and generates
 * a TypeScript module with skill content as a string map.
 *
 * Usage: bun scripts/generate-skill-bundle.ts
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const EXTERNAL_SKILLS_DIR = join(ROOT, "packages/core/src/skills/external");
const OUTPUT_FILE = join(EXTERNAL_SKILLS_DIR, "content.generated.ts");

// Skill IDs and their source paths relative to EXTERNAL_SKILLS_DIR
const SKILL_SOURCES: Record<string, string> = {
  "judgment-day": "judgment-day/SKILL.md",
  "cognitive-doc-design": "cognitive-doc-design/SKILL.md",
  "comment-writer": "comment-writer/SKILL.md",
};

function escapeStringForTs(str: string): string {
  // Escape backticks, ${, and backslashes for template literal
  return str
    .replace(/\\/g, "\\\\")
    .replace(/\$/g, "\\$")
    .replace(/`/g, "\\`")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

function generateBundle(): void {
  const contentMap: Record<string, string> = {};
  const errors: string[] = [];

  for (const [skillId, sourcePath] of Object.entries(SKILL_SOURCES)) {
    const fullPath = join(EXTERNAL_SKILLS_DIR, sourcePath);

    if (!existsSync(fullPath)) {
      errors.push(`Skill ${skillId} not found at ${fullPath}`);
      continue;
    }

    try {
      const content = readFileSync(fullPath, "utf-8").trim();
      if (!content) {
        errors.push(`Skill ${skillId} at ${sourcePath} is empty`);
        continue;
      }
      contentMap[skillId] = content;
    } catch (err) {
      errors.push(`Failed to read ${sourcePath}: ${err}`);
    }
  }

  // Check for declared skills with missing/empty content
  for (const skillId of Object.keys(SKILL_SOURCES)) {
    if (!contentMap[skillId]) {
      errors.push(`Skill ${skillId} has no content in generated bundle`);
    }
  }

  if (errors.length > 0) {
    console.error("Error generating skill bundle:");
    for (const err of errors) {
      console.error(`  - ${err}`);
    }
    process.exit(1);
  }

  // Generate TypeScript module
  const tsContent = `/**
 * Generated skill content bundle.
 *
 * AUTO-GENERATED FILE — DO NOT EDIT
 * Generated by: scripts/generate-skill-bundle.ts
 */

// prettier-ignore
export const SKILL_CONTENT: Record<string, string> = {
${Object.entries(contentMap)
  .map(([skillId, content]) => `  "${skillId}": \`${escapeStringForTs(content)}\`,`)
  .join("\n")}
};
`;

  // Write output
  const outputDir = dirname(OUTPUT_FILE);
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  writeFileSync(OUTPUT_FILE, tsContent, "utf-8");

  console.log(`Generated skill bundle: ${OUTPUT_FILE}`);
  console.log(`  Skills bundled: ${Object.keys(contentMap).join(", ")}`);
}

// Run if called directly
if (import.meta.main) {
  generateBundle();
}