import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

import { computePiExtensionSourceDigest, piExtensionAssetPath, PI_EXTENSION_BUNDLES } from "./generate-pi-extension-assets";

const nodePath = Bun.which("node");

describe("generated Pi extension bundles", () => {
  test("child shell uses the supported external native module, not a bundled Pi runtime", () => {
    const bundle = readFileSync(piExtensionAssetPath("deck-subagents"), "utf8");
    expect(bundle).toContain('import("@earendil-works/pi-coding-agent")');
    expect(bundle).not.toContain("node_modules/@earendil-works/pi-coding-agent");
  });
  test.skipIf(!nodePath)("generated factory preserves parent tools and child recursion guard under Node", async () => {
    const path = piExtensionAssetPath("deck-subagents");
    const child = Bun.spawn([nodePath!, "--input-type=module", "-e", `const {default: factory} = await import(${JSON.stringify(pathToFileURL(path).href)}); const names=[]; const pi={registerTool:t=>names.push(t.name),registerCommand(){},on(){}}; await factory(pi); process.env.DECK_PI_CHILD="1"; await factory(pi); console.log(JSON.stringify(names));`], { stdout: "pipe", stderr: "pipe", stdin: "ignore", env: { PATH: process.env.PATH ?? "" } });
    const [stdout, stderr] = await Promise.all([new Response(child.stdout).text(), new Response(child.stderr).text()]);
    expect({ code: await child.exited, stdout: stdout.trim(), stderr }).toEqual({ code: 0, stdout: '["subagent"]', stderr: "" });
  });
  for (const name of PI_EXTENSION_BUNDLES) {
    const path = piExtensionAssetPath(name);
    const present = existsSync(path);
    (present ? test : test.skip)(`${name} is up to date with its sources (regenerate with scripts/generate-pi-extension-assets.ts)`, () => {
      const header = readFileSync(path, "utf-8").split("\n").slice(0, 2);
      expect(header[0]).toContain("Generated by scripts/generate-pi-extension-assets.ts");
      expect(header[1]).toBe(`// source-sha256:${computePiExtensionSourceDigest()}`);
    });
    (present && nodePath ? test : test.skip)(`${name} loads under Node (Pi's runtime) and exports a factory`, async () => {
      const child = Bun.spawn([nodePath!, "--input-type=module", "-e", `const m = await import(${JSON.stringify(pathToFileURL(path).href)}); console.log(typeof m.default);`], { stdout: "pipe", stderr: "pipe", stdin: "ignore", env: { PATH: process.env.PATH ?? "" } });
      const [stdout, stderr] = await Promise.all([new Response(child.stdout).text(), new Response(child.stderr).text()]);
      expect({ code: await child.exited, stdout: stdout.trim(), stderr: stderr.slice(0, 300) }).toEqual({ code: 0, stdout: "function", stderr: "" });
    });
    (present ? test : test.skip)(`${name} never uses the Bun-only import.meta.require`, () => {
      expect(readFileSync(path, "utf-8")).not.toContain("import.meta.require");
    });
  }
});
