import { resolve } from "node:path";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const root = resolve(import.meta.dir, "..");
const entries = [
  {
    input: resolve(root, "packages/adapter-opencode/assets/opencode/plugins/developer-team-execution.ts"),
    output: resolve(root, "packages/adapter-opencode/assets/opencode/plugins/developer-team-execution.generated.js"),
  },
  {
    input: resolve(root, "packages/adapter-pi/assets/pi/extensions/developer-team-execution.ts"),
    output: resolve(root, "packages/adapter-pi/assets/pi/extensions/developer-team-execution.generated.js"),
  },
] as const;

for (const entry of entries) {
  const build = Bun.spawnSync({
    cmd: ["bun", "build", entry.input, "--target=bun", "--format=esm", "--minify", `--outfile=${entry.output}`],
    cwd: root,
    stdout: "pipe",
    stderr: "pipe",
  });
  if (!build.success) {
    throw new Error(new TextDecoder().decode(build.stderr));
  }
  const sourceDigest = createHash("sha256").update(readFileSync(entry.input)).digest("hex");
  const bundle = readFileSync(entry.output, "utf-8");
  writeFileSync(entry.output, `// Generated by scripts/generate-runner-execution-assets.ts; do not edit.\n// source-sha256:${sourceDigest}\n${bundle}`, "utf-8");
}
