import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

/**
 * Bundles the Deck Pi extensions (TypeScript sources under `packages/adapter-pi/src/pi-extensions`) into plain
 * Node-loadable ESM assets under `packages/adapter-pi/assets/pi/extensions/`. Pi runs on Node, so the target is
 * `node` (never `bun`: Bun-targeted bundles use `import.meta.require`, which Node lacks).
 *
 * The output is not minified and carries the SHA-256 of every non-test source file, so a test can detect a stale
 * bundle without depending on the bundler version. Regenerate with `bun run scripts/generate-pi-extension-assets.ts`.
 */
const root = resolve(import.meta.dir, "..");
const SOURCE_DIR = "packages/adapter-pi/src/pi-extensions";
const OUTPUT_DIR = "packages/adapter-pi/assets/pi/extensions";

export const PI_EXTENSION_BUNDLES = ["deck-memory", "deck-subagents", "deck-tool-policy"] as const;
export type PiExtensionBundleName = (typeof PI_EXTENSION_BUNDLES)[number];

export type PiExtensionAssetResult = { name: PiExtensionBundleName; output: string; sourceDigest: string };

function listSources(directory: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(directory).sort()) {
    const path = join(directory, entry);
    if (statSync(path).isDirectory()) files.push(...listSources(path));
    else if (entry.endsWith(".ts") && !entry.endsWith(".test.ts")) files.push(path);
  }
  return files;
}

/** Files outside `pi-extensions/` that the bundles import; included in the digest so the staleness test sees them. */
const EXTERNAL_SOURCES = ["packages/adapter-pi/src/pi-mcp-catalog.ts", "packages/core/src/owned-tools/rtk-hook.ts"] as const;

export function computePiExtensionSourceDigest(projectRoot = root): string {
  const sourceRoot = resolve(projectRoot, SOURCE_DIR);
  const hash = createHash("sha256");
  for (const external of EXTERNAL_SOURCES) {
    hash.update(external);
    hash.update("\0");
    hash.update(readFileSync(resolve(projectRoot, external)));
    hash.update("\0");
  }
  for (const file of listSources(sourceRoot)) {
    hash.update(relative(sourceRoot, file).split("\\").join("/"));
    hash.update("\0");
    hash.update(readFileSync(file));
    hash.update("\0");
  }
  return hash.digest("hex");
}

export function piExtensionAssetPath(name: PiExtensionBundleName, projectRoot = root): string {
  return resolve(projectRoot, OUTPUT_DIR, `${name}.generated.js`);
}

export async function generatePiExtensionAssets(options: { root?: string; names?: readonly PiExtensionBundleName[] } = {}): Promise<PiExtensionAssetResult[]> {
  const projectRoot = options.root ?? root;
  const sourceDigest = computePiExtensionSourceDigest(projectRoot);
  const results: PiExtensionAssetResult[] = [];
  for (const name of options.names ?? PI_EXTENSION_BUNDLES) {
    const entry = resolve(projectRoot, SOURCE_DIR, "entries", `${name}.ts`);
    const build = await Bun.build({ entrypoints: [entry], target: "node", format: "esm", minify: false, sourcemap: "none" });
    if (!build.success || build.outputs.length !== 1) {
      throw new Error(`Bundling ${name} failed: ${build.logs.map((log) => log.message).join("; ")}`);
    }
    const bundle = await build.outputs[0]!.text();
    if (bundle.includes("import.meta.require")) throw new Error(`${name} bundle uses the Bun-only import.meta.require; it must load under Node.`);
    const output = piExtensionAssetPath(name, projectRoot);
    writeFileSync(output, `// Generated by scripts/generate-pi-extension-assets.ts; do not edit.\n// source-sha256:${sourceDigest}\n${bundle}`, "utf-8");
    results.push({ name, output, sourceDigest });
  }
  return results;
}

if (import.meta.main) {
  try {
    const present = PI_EXTENSION_BUNDLES.filter((name) => {
      try { statSync(resolve(root, SOURCE_DIR, "entries", `${name}.ts`)); return true; } catch { return false; }
    });
    for (const result of await generatePiExtensionAssets({ names: present })) console.log(`generated ${result.output}`);
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
