#!/usr/bin/env bun
/**
 * Build info generation script.
 *
 * Generates build-time metadata (version, commit, date, target, channel)
 * into apps/cli/src/runtime/build-info.generated.ts.
 *
 * Usage:
 *   bun run scripts/generate-build-info.ts [--version <semver>] [--target <platform>] [--channel <channel>]
 *
 * Options:
 *   --version   Version string (semver). If omitted, reads from package.json
 *   --target   Target platform (e.g., linux-x64, darwin-arm64). If omitted, uses node os.platform()+arch()
 *   --channel  Release channel (stable|beta|dev). If omitted, defaults to "stable"
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";

const PROJECT_ROOT = path.resolve(import.meta.dir, "..");
const OUTPUT_FILE = path.join(PROJECT_ROOT, "apps/cli/src/runtime/build-info.generated.ts");
const PACKAGE_JSON = path.join(PROJECT_ROOT, "package.json");

interface Args {
  version?: string;
  target?: string;
  channel?: "stable" | "beta" | "dev";
  help?: boolean;
}

function parseArgs(argv: string[]): Args {
  const args: Args = {};
  const rawArgs = argv.slice(2); // Skip bun and script path

  let i = 0;
  while (i < rawArgs.length) {
    const arg = rawArgs[i]!;

    if (arg === "--help" || arg === "-h") {
      args.help = true;
      break;
    }

    if (arg === "--version") {
      if (i + 1 < rawArgs.length) {
        i++;
        args.version = rawArgs[i]!;
      }
    } else if (arg === "--target") {
      if (i + 1 < rawArgs.length) {
        i++;
        args.target = rawArgs[i]!;
      }
    } else if (arg === "--channel") {
      if (i + 1 < rawArgs.length) {
        i++;
        const channel = rawArgs[i]!;
        if (channel === "stable" || channel === "beta" || channel === "dev") {
          args.channel = channel as "stable" | "beta" | "dev";
        } else {
          console.error(`Invalid channel: ${channel}. Use stable, beta, or dev.`);
          process.exit(1);
        }
      }
    } else if (!arg.startsWith("-")) {
      // Allow positional version for convenience
      if (!args.version) {
        args.version = arg;
      }
    }
    i++;
  }

  return args;
}

function getGitCommit(): string {
  try {
    const proc = Bun.spawnSync(["git", "rev-parse", "--short", "HEAD"], {
      cwd: PROJECT_ROOT,
    });
    if (proc.success && proc.stdout) {
      return new TextDecoder().decode(proc.stdout).trim();
    }
  } catch {
    // Ignore - fallback to unknown
  }
  return "unknown";
}

function getVersionFromPackageJson(): string {
  try {
    const content = fs.readFileSync(PACKAGE_JSON, "utf-8");
    const pkg = JSON.parse(content);
    return pkg.version || "0.0.0";
  } catch {
    return "0.0.0";
  }
}

function generateBuildInfo(args: Args): string {
  const version = args.version ?? getVersionFromPackageJson();
  const commit = getGitCommit();
  const date = new Date().toISOString().split("T")[0]!;
  const target = args.target ?? `${os.platform()}-${os.arch()}`;
  const channel = args.channel ?? "stable";

  return `/**
 * Generated build info for production builds.
 *
 * Auto-generated by scripts/generate-build-info.ts.
 * Do not edit manually.
 */

import type { BuildInfo } from "./build-info.js";

export const BUILD_INFO: BuildInfo = {
  version: "${version}",
  commit: "${commit}",
  date: "${date}",
  target: "${target}",
  channel: "${channel}",
} as const;
`;
}

function main() {
  const args = parseArgs(process.argv);

  if (args.help) {
    console.log(`Generate build info for deck CLI.

Usage:
  bun run scripts/generate-build-info.ts [options] [version]

Options:
  --version <semver>   Version string (semver). If omitted, reads from package.json
  --target <platform>  Target platform (e.g., linux-x64, darwin-arm64)
  --channel <channel> Release channel: stable, beta, or dev (default: stable)
  --help, -h         Show this help message

Examples:
  bun run scripts/generate-build-info.ts
  bun run scripts/generate-build-info.ts --version 1.2.3 --target darwin-arm64 --channel beta
  bun run scripts/generate-build-info.ts 1.2.3
`);
    process.exit(0);
  }

  const content = generateBuildInfo(args);
  fs.writeFileSync(OUTPUT_FILE, content, "utf-8");

  console.log(`Generated: ${OUTPUT_FILE}`);
}

main();